[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[package]
name = "prs_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "1.8.0"
clearscreen = "1.0.10"